apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-169442138
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-169442138
    app.kubernetes.io/part-of: test-app-169442138
  name: go-169442138
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-169442138
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-169442138
    spec:
      containers:
      - env:
        - name: TEST_ENV_VAR
          value: Test go app
        image: quay.io/redhat-user-workloads/skhileri-tenant/test-app-169442138/go-169442138@sha256:47b6473333e3b2b974282366c4bc8024d0c2cf426c8d46995bc92bda8ac6e41e
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
