apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-169442138
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-169442138
    app.kubernetes.io/part-of: test-app-169442138
  name: go-169442138tpad
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: go-169442138
    weight: null
status: {}
